### ISSUE TITLE
cannot import name conf

### ISSUE THREAD

**Issue by Jinnial** [UmSenhorQualquer/pyforms#37]
I'm having an issue after the installation of PyForms using the example code. I copied and pasted it into Visual Studio (I have VS use the local python install) and this error comes up:

![image](https://cloud.githubusercontent.com/assets/10831565/20806481/b4794e1e-b7c0-11e6-9559-eac95ebd815d.png)

Not sure where is going wrong though. I get the same problem when I run my code through IDLE. Also, this is the values of the locals:

__builtins__
`{'ArithmeticError': <type 'exceptions.Ar...ticError'>, 'AssertionError': <type 'exceptions.As...ionError'>, 'AttributeError': <type 'exceptions.At...uteError'>, 'BaseException': <type 'exceptions.Ba...xception'>, 'BufferError': <type 'exceptions.Bu...ferError'>, 'BytesWarning': <type 'exceptions.By...sWarning'>, 'DeprecationWarning': <type 'exceptions.De...nWarning'>, 'EOFError': <type 'exceptions.EOFError'>, 'Ellipsis': Ellipsis, 'EnvironmentError': <type 'exceptions.En...entError'>, 'Exception': <type 'exceptions.Exception'>, 'False': False, 'FloatingPointError': <type 'exceptions.Fl...intError'>, 'FutureWarning': <type 'exceptions.Fu...eWarning'>, ...}`

__name__
`__main__`

And here is the actual code:

```
"""  Title: CIS 120's Final Project w/ GUI using PyForms
     Date: November 30th, 2016
     Author: Brenden Reeves
     Class: CIS 120 - Mrs. Markly 
"""

import pyforms
from   pyforms          import BaseWidget
from   pyforms.Controls import ControlText
from   pyforms.Controls import ControlButton

class WelcomeWindow(BaseWidget):
    
    def __init__(self):
        super(SimpleExample1,self).__init__('Simple example 1')

        #Definition of the forms fields
        self._firstname = ControlText('First name', 'Default value')
        self._middlename = ControlText('Middle name')
        self._lastname = ControlText('Lastname name')
        self._fullname = ControlText('Full name')
        self._button = ControlButton('Press this button')

    if __name__ == "__main__":
    pyforms.startApp(SimpleExample1)
```

**Comment by ron-mypy** [comment]
I'm getting the same error on Debian(unstable). It seems that something in the latest pysettings has changed and broken PyForms.

``` python
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Dec  2 16:34:09 2016

@author: qwix
"""

import pyforms
from   pyforms          import BaseWidget
from   pyforms.Controls import ControlText
from   pyforms.Controls import ControlButton

class SimpleExample1(BaseWidget):

    def __init__(self):
        super(SimpleExample1,self).__init__('Simple example 1')

        #Definition of the forms fields
        self._firstname     = ControlText('First name', 'Default value')
        self._middlename    = ControlText('Middle name')
        self._lastname      = ControlText('Lastname name')
        self._fullname      = ControlText('Full name')
        self._button        = ControlButton('Press this button')


#Execute the application
if __name__ == "__main__":   pyforms.startApp( SimpleExample1 )
```
pysettings was an unmet dependency. You should add this to the basic instructions.

```
qwix@hodor:/code/python/mypyform$ python3 test.py
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    import pyforms
  File "/usr/local/lib/python3.5/dist-packages/pyforms/__init__.py", line 4, in <module>
    from pysettings import conf;
ImportError: No module named 'pysettings'
qwix@hodor:/code/python/mypyform$ sudo pip3 install pysettings
Collecting pysettings
  Downloading PySettings-0.1.90.tar.gz
Building wheels for collected packages: pysettings
  Running setup.py bdist_wheel for pysettings ... done
  Stored in directory: /home/qwix/.cache/pip/wheels/a8/9d/1c/cdf76403a5cdd6a067e8a7ad0633dbcdd22e003088fdd4cb04
Successfully built pysettings
Installing collected packages: pysettings
Successfully installed pysettings-0.1.90
qwix@hodor:/code/python/mypyform$ python3 test.py
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    import pyforms
  File "/usr/local/lib/python3.5/dist-packages/pyforms/__init__.py", line 4, in <module>
    from pysettings import conf;
ImportError: cannot import name 'conf'
root@hodor:/home/qwix/code/python/mypyform# sudo pip3 install --upgrade --force-reinstall pyforms
Collecting pyforms
Installing collected packages: pyforms
  Found existing installation: PyForms 0.1.7.3
    Uninstalling PyForms-0.1.7.3:
      Successfully uninstalled PyForms-0.1.7.3
Successfully installed pyforms-0.1.7.3
qwix@hodor:/code/python/mypyform$ python3 test.py
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    import pyforms
  File "/usr/local/lib/python3.5/dist-packages/pyforms/__init__.py", line 4, in <module>
    from pysettings import conf;
ImportError: cannot import name 'conf'
```

**Comment by JBauto** [comment]
Both PyForms and PySettings aren't updated to the latest version in pip. You should install both using the main repos...

- pip install git+https://github.com/UmSenhorQualquer/pyforms.git --upgrade
- pip install git+https://github.com/UmSenhorQualquer/pysettings.git --upgrade

**Comment by Jinnial** [comment]
Thank you! It's all working now.
