### ISSUE TITLE
ImportError: cannot import name ControlPlayer

### ISSUE THREAD

**Issue by cmooreml** [UmSenhorQualquer/pyforms#62]
Using this example:

https://github.com/UmSenhorQualquer/pyforms/tree/master/tutorials/1.SimpleExamples/ComputerVisionAlgorithmExample

File "gui_test.py", line 4, in <module>
    from __init__ import *
  File "/Users/cmoore/Documents/GitHub/feature_extraction/__init__.py", line 18, in <module>
    from pyforms.Controls import ControlPlayer
ImportError: cannot import name ControlPlayer

OSX/Macbook Pro/MacPorts

Related: https://github.com/UmSenhorQualquer/pyforms/issues/42

**Comment by cmooreml** [comment]
Fixed this by adding this to my main class and fixing the error with 

```
import logging
logging.basicConfig()
```

```
mlla2126:feature_extraction cmoore$ python gui_test.py
WARNING:/Library/Python/2.7/site-packages/pyforms/Controls.pyc:QtWebKit lib not installed or not working properly
WARNING:/Library/Python/2.7/site-packages/pyforms/Controls.pyc:Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pyforms/Controls.py", line 34, in <module>
    from pyforms.gui.Controls.ControlWeb import ControlWeb
  File "/Library/Python/2.7/site-packages/pyforms/gui/Controls/ControlWeb.py", line 15, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEngineView as QWebView
ImportError: No module named QtWebEngineWidgets

```
