### ISSUE TITLE
ModuleNotFoundError: No module named 'cv2'

### ISSUE THREAD

**Issue by jhb** [UmSenhorQualquer/pyforms#77]
Just trying to use pyforms for the first time. When installing using virtualenv/python3.6 I came across a dependency on cv2:
~~~~
No module named 'cv2'
Traceback (most recent call last):
  File "/home/joerg/tmp/pf/lib/python3.6/site-packages/pyforms/controls.py", line 47, in <module>
    from pyforms.gui.controls.ControlOpenGL 				import ControlOpenGL
  File "/home/joerg/tmp/pf/lib/python3.6/site-packages/pyforms/gui/controls/ControlOpenGL.py", line 30, in <module>
    from pyforms.gui.controls.control_player.VideoGLWidget import VideoGLWidget
  File "/home/joerg/tmp/pf/lib/python3.6/site-packages/pyforms/gui/controls/control_player/VideoGLWidget.py", line 8, in <module>
    from pyforms.gui.controls.control_player.AbstractGLWidget import AbstractGLWidget
  File "/home/joerg/tmp/pf/lib/python3.6/site-packages/pyforms/gui/controls/control_player/AbstractGLWidget.py", line 7, in <module>
    import logging, cv2
~~~~
This can be fixed by

`pip install opencv-python`

My feeling is that it should be made a requirement though.

**Comment by UmSenhorQualquer** [comment]
Definitely. Version 4 will have it.
